### ISSUE TITLE
When will the code be available?

### ISSUE THREAD

**Issue by antorsae** [tae-jun/resemul#1]

**Comment by tae-jun** [comment]
Sorry for the late response! I was on a vacation.

I planned to upload the code when my paper was accepted.
And I wanted to upgrade Keras and TensorFlow to the latest version.

However, because of [the issue](https://github.com/keras-team/keras/issues/8430) I couldn't make it...
Now I plan to upload code with Keras 2.0.5.
Because I use `TFRecord` my code varies from Keras 2.0.7 (they officially support TFRecord from here), I should re-write the code.

Sorry for being late!
I will upload it in 2 weeks.
Thanks 😄

**Comment by tae-jun** [comment]
The codes are now available! Please check! 😄
